### ISSUE TITLE
Scherm achter Profiel/Account bevat issues

### ISSUE THREAD

**Issue by JulianBaarsDAT** [TOP-Squad/resume-issues#100]
Pas profiel aan via Account knop:
- Je komt in een Engelstalig scherm terecht (nergens anders gebruikt dan behalve bij Inlogscherm - al melding van). 
- Er is ook geen header op dit scherm. 
- In de subschermen waarop de Cancel button verschijnt heeft erop klikken geen enkel effect. Behalve bij Authenticator waarbij een nieuwe QR-code wordt getoond.

**Comment by jroosing** [comment]
Profiel aanpassen en login scherm zijn nu in het nederlands.

De annuleer knop annuleert niet het scherm, maar alleen de getypte wijzigingen.

**Comment by sdahlberg** [comment]
Specifiek voor de taal een nieuw issue aangemaakt: https://github.com/TOP-Squad/resume-issues/issues/102. Bottom line: alles standaard Nederlands, en geen taalkeuze aanbieden.

De account pagina staat in low-maintenance mode, aangezien we die op termijn willen integreren binnen de cv generator zelf.
