### ISSUE TITLE
Verwijderen van een rol wordt altijd gedaan ongeacht het antwoord op de Weet u het zeker? vraag

### ISSUE THREAD

**Issue by henri815** [TOP-Squad/resume-issues#126]
Als je als gebruiker op acceptatie een rol wil verwijderen maar toch op nee klikt bij de controle vraag "Weet u het zeker" dan wordt de rol alsnog verwijderd

Hetzelfde gedrag wordt ook vertoond bij het wisselen van Mijn CV naar het Beheer menu

![afbeelding](https://github.com/TOP-Squad/resume-issues/assets/93133111/6a014548-918b-42a1-a93d-5126f3ca914e)

**Comment by sdahlberg** [comment]
@henri815 Ik kan het niet naspelen. Is er nog een randvoorwaarde van kracht?

**Comment by henri815** [comment]
Hier de stappen die ik neem om het te reproduceren (CV tool acceptatie DAT):
- Open Mijn CV en ga naar Pitches
- Voeg een rol toe 
- Selecteer de prullenbak icoon om de toegevoegde rol te verwijderen
- Controle vraag verschijnt "Weet u het zeker?", selecteer nu "Nee"

Verwacht:
- toegevoegde rol blijft staan bij Pitches

Werkelijk:
- Toegevoegde rol is verwijderd

**Comment by sdahlberg** [comment]
Fixed
