### ISSUE TITLE
Foto wordt 90 graden gedraaid (CCW) bij opnieuw openen Mijn CV

### ISSUE THREAD

**Issue by henri815** [TOP-Squad/resume-issues#128]
Wanneer een CV met een reeds toegevoegde foto in de Personalia wordt geopend dan wordt de toegevoegde foto 90 graden linksom getoond. Na bewerken en opnieuw opslaan wordt de foto weer 'goed' gezet. In de download versie van de CV wordt de foto eveneens gedraaid getoond

Om te reproduceren (ACC DAT):
- voeg een foto toe aan de personalia in een CV, sla deze op
- Zet het tonen van de avatar op 'aan'
- ga naar Download cv en vervolgens terug naar Mijn CV en open de personalia

Resultaat:
Foto is 90 graden gedraaid en 

Verwacht: 
Foto wordt in de originele opgeslagen stand getoond
In de download versie van de CV wordt de foto gedraaid toegevoegd in het word document

**Comment by sdahlberg** [comment]
@henri815 het lukt me niet om deze te reproduceren. MIsschien ligt het aan de foto, kun je deze bij het issue uploaden?

**Comment by henri815** [comment]
![image_67207681](https://github.com/TOP-Squad/resume-issues/assets/93133111/d8a30278-3590-417b-aaa6-11696744e837)

**Comment by sdahlberg** [comment]
fixed
