### ISSUE TITLE
Nieuwe rollen in beheermenu worden willekeurig gesorteerd

### ISSUE THREAD

**Issue by henri815** [TOP-Squad/resume-issues#132]
Als in de acceptatie van DAT als beheerder meerdere nieuwe rollen worden toegevoegd (zie afbeelding hieronder) dan worden deze vervolgens, ogenschijnlijk, willekeurig gesorteerd. 

![afbeelding](https://github.com/TOP-Squad/resume-issues/assets/93133111/aff66063-0d6e-4ae8-aee3-1a26bea34b3a)

**Comment by sdahlberg** [comment]
fixed
