### ISSUE TITLE
Tooltip bij pitch word niet juist getoond

### ISSUE THREAD

**Issue by whdeveloper** [TOP-Squad/resume-issues#171]
Bij de tooltip onder de kop pitches is de breedte van deze tooltip de volledige breedte van het scherm. Ook valt het pijltje niet onder de 'i' knop, waardoor het lijkt alsof er iets aan formatting mist

**Comment by sdahlberg** [comment]
Opgelost, pijltje weggelaten, en de breedte minder breed gemaakt.
