### ISSUE TITLE
Gebruik distroless jre image

### ISSUE THREAD

**Issue by sdahlberg** [TOP-Squad/resume-issues#20]
jlink

**Comment by jroosing** [comment]
Een distroless image gaat niet werken.

De base image (distroless) heeft een entrypoint van java -jar. 
Verder is er geen shell / bash aanwezig en kan je geen shell scripts uitvoeren. 

Hetgeen dat dus een blocker is alvorens we hier iets mee kunnen is een wait-for-it, danwel een retry mechanisme in de applicatie
