### ISSUE TITLE
Custom field values hebben max lengte van 255

### ISSUE THREAD

**Issue by sdahlberg** [TOP-Squad/resume-issues#83]
Beetje krap wellicht? 
En de foutmelding in de gui is belabberd.

**Comment by sdahlberg** [comment]
Geldt overigens voor alle velden. Validatie wordt alleen in de backend afgedwongen.

**Comment by cwesterhof** [comment]
Ik constateer een kleine meer cosmetische issue mbt de bullet velden. Als ik de eerdere communicatie omtrent de aanpassingen op acceptance in ogenschouw neem valt dit onder deze issue.

De aanpassing zou zijn dat er een maximale grootte en een maximaal aantal is en dat dit ook als zodanig onder het veld zou zijn aangegeven. Eerste tests wijzen uit dat de maximale grootte inderdaad is toegepast maar dat door een extra "Enter" toe te passen het lijkt alsof er nog een extra regel mogelijk is. Hij is niet te gebruiken als extra regel maar hij staat wel als zodanig onder het veld. 

Zie de afbeelding voor verduidelijking.

<img width="552" alt="image" src="https://github.com/TOP-Squad/resume-issues/assets/21332918/939fb1bf-9300-429f-8e37-a99ffcc2f096">

**Comment by sdahlberg** [comment]
fixed
