### ISSUE TITLE
Kunnen verwijderen tenants, zodat de lege test-tenants op acce en de oude demo op prod weg kunnen

### ISSUE THREAD

**Issue by sdahlberg** [TOP-Squad/resume-issues#93]
- Realm weggooien in keycloak via REST (KeycloakRealmService)
- Schema weggooien dmv DROP SCHEMA ..
- Row weggooien van betreffende tenant in tenant tabel
- DataSource unregister en vrijgeven connection pool voor deze tenant

Centrale ingang: TenantAdminCrudController
delegeren naar  TenantOrchestrator

Alleen user met rol manage-tenants mag dit doen
- SecurityComponentTest

+ Frontend

**Comment by whdeveloper** [comment]
POST - /verifyDeleteTenant
return base64 string with username, realm, role, timestamp

DELETE - /deleteTenant
header with base64 string
decode base64 string if it is the same username, realm, role and the timestamp is x time ago
