### ISSUE TITLE
Wijziging gegevens nieuwe gebruiker niet direct getoond in Overzicht gebruikers

### ISSUE THREAD

**Issue by JulianBaarsDAT** [TOP-Squad/resume-issues#94]
Stappen:
Maak een nieuwe gebruiker aan.  Doe een wijziging in de gegevens van de nieuwe gebruiker. In dit geval de Voornaam gewijzigd. Wijziging opgeslagen.

Resultaat:
Netjes komt er een melding dat de wijziging is opgeslagen. Maar wijziging is niet zichtbaar in Overzicht gebruikers. Laatst gewijzigd time-stamp is ook niet gewijzigd!  Ook na refresh van pagina wordt wijziging niet getoond in overzicht. Time-stamp ook niet. Openen gegevens gebruiker toont wel de wijziging.

**Comment by sdahlberg** [comment]
Voornaam en achternaam uit account wordt nu getoond in tabel. Tabel heeft nu 2 header rows om onderscheidt te maken tussen accountgegevens en cv gegevens. Hier kunnen alleen accountgegevens aangepast worden, geen cv gegevens.
