### ISSUE TITLE
Inconsistent gebruik iconen en buttons

### ISSUE THREAD

**Issue by JulianBaarsDAT** [TOP-Squad/resume-issues#99]
De functionaliteit om een rol aan te passen (of te verwijderen) is via Iconen (uiterst rechts op de pagina) en niet zoals op Gebruikers overzicht via buttons. Dat is inconsistent uit gebruikers oogpunt.

**Comment by sdahlberg** [comment]
Nog niet duidelijk wat we willen. De knoppen bij gebruikers is recentelijk gekozen, omdat knoppen de leesbaarheid en daarmee de inzichtelijkheid vergroot. De acties zijn wel zo één klik minder toegankelijk. Móchten we een keer meerdere rollen tegelijk weg willen gooien zou dat onhandig zijn. Daar is alleen momenteel geen reden toe.
Eventueel zouden de knoppen er al wel disabled kunnen staan buiten de tabel, bijv. naast 'Nieuwe rol', en dat je met checkboxen aan de begin van de regel een selectie maakt. 
Dit gezegd hebbende zou ik voor nu voor knoppen gaan. Ze verplaatsen zou altijd nog kunnen.

**Comment by sdahlberg** [comment]
Alles aangepast naar knoppen
